### ISSUE TITLE
Resources are 2 years old

### ISSUE THREAD

**Issue by VividVisions** [codeeu/codeeu-resources#7]
Where can I find current logos/promotional material?

**Comment by ioana-chiorean** [comment]
@VividVisions keep an eye on https://github.com/codeeu/codeeu-resources/pull/8

**Comment by ioana-chiorean** [comment]
hey @VividVisions - we updated the resources - let me know if you need something more specific.

**Comment by ioana-chiorean** [comment]
Can we close this one? cc @alainvd ?

**Comment by alainvd** [comment]
Sure. It id done :)
